### PR TITLE
Initial setup with suggested CircleCI config

### PR DESCRIPTION
**Pull request by Firesphere**
Added a test for the primary DB field

Added some configuration for scrutinizer/CircleCI (which I personally prefer, but it's up to you of course!), CodeCov and CodeClimate.

### CODE REVIEW

**Comment by fonsekaean** [comment]
@Firesphere got conflicts :)

**Comment by Firesphere** [comment]
As expected from a comment I made earlier :) Just a bit.

p.s.
CircleCI is free for Open Source projects, which is why I'm suggesting it. I personally like it more, if you want help getting it set up, throw me an email :)

**Comment by fonsekaean** [comment]
point me in the right direction for circleCI

**Comment by Firesphere** [comment]
Hey Nivanka,

You need to go to circleci.com and log in with GitHub.
After that, go to your profile via the top right menu and set up github integration with your organisation.

When that's done, on the top left, select your organisation and go to Projects on the left.
It should say no projects yet. Click on "Add Project", select the repository you want CircleCI to run, and you're all set up :)

**Comment by Firesphere** [comment]
More information can be found in the documentation:
https://circleci.com/docs/2.0/

**Comment by fonsekaean** [comment]
Thanks merging in

**Pull request merged**
