### PR TITLE
Feature/settings as static yml

### PR DESCRIPTION
**Pull request by Firesphere**
Using a static for such an array, loaded from `Config` is faster and easier to configure for other users, by loading their own configuration in a YML.

### CODE REVIEW

**Comment by Firesphere** [comment]
I have no idea why the other commits are in here, but it seems to be fine to merge?

**Comment by fonsekaean** [comment]
@Firesphere I see that your PR is to take out all the configs from the YML files. However what we need here is to have multiple configs options, and set them up for different editor instances, and making it to YML will add a restriction to only use it globally. 

So having a protected variable for configs is still good I suppose. Do you see anything different ?

**Comment by Firesphere** [comment]
I did not take that in to account, to be honest, let me think about it? That scenario completely bypassed me (oops)

**Comment by fonsekaean** [comment]
@Firesphere  Any ideas on this one ?

**Comment by Firesphere** [comment]
Sorry, I've not yet had the time to have a proper look at it again yet! I'll try to find some time tomorrow (NZ time)

**Comment by michalkleiner** [comment]
It can be a global config as long as we keep the option to override it per instance, right?

**Comment by fonsekaean** [comment]
@michalkleiner that's right. It needs to be configurable per instance

**Comment by Firesphere** [comment]
@fonsekaean What do you mean with "per instance", do you mean "per CMSField" or "per Project"?

If it's the latter, this solution works, as a mysite config would override it.

**Comment by fonsekaean** [comment]
Per Config instance

**Comment by Firesphere** [comment]
Right. I'll have to come up with something a bit more elaborate then. I still prefer the usage of yml over inline though, as it's easier to override from a SilverStripe perspective

**Comment by Firesphere** [comment]
The whole `config`, `current` etc. settings are a bit confusing though. They're pointing all over the place and not really making clear what they're for. 

e.g. the `set_active` is setting `current` (which is supposed to be a string) to be a full config, which doesn't make sense, because get_active returns the active config that's in `configs` array.
I think there's some syntax errors that needs resolving. 

I've pushed a refactor plus commenting update, see what you think of it? It allows for customised, different configs to be set per field (almost, I need to get to the EditorField itself still)

**Comment by fonsekaean** [comment]
Hello @Firesphere after merginig this in i found out there has been some issues which we had not seen. I've fixed them now. 

Check these commits https://github.com/SilverStripers/markdownfield/commit/16c1aa9a301848eedc6bfbd49d0981756ecd0955

**Pull request merged**
