### PR TITLE
Fixes for media/embed functionality

### PR DESCRIPTION
**Pull request by oilee80**
If `window.InsertMediaModal` or `window.InsertEmbedModal` where undefined then JS would error and markdown field wouldn't appear

### CODE REVIEW

**Comment by fonsekaean** [comment]
@oilee80 thanks for this. 

Can you tell me how did do recreate the issue as well please ?

**Comment by oilee80** [comment]
Hi @fonsekaean,
Sorry I've just re-tried with a new vanilla SS4 install and it appears to be working fine.
Closing

**Comment by fonsekaean** [comment]
@oilee80 cool, thanks for confirming.

**Comment by oilee80** [comment]
Sorry @fonsekaean 
Found where the issue is, if you don't have the SS asset-admin then you get the error

**Comment by fonsekaean** [comment]
@oilee80 nice one. I think this leads to some interesting discussion then. 

1. Do we support the asset-admin in any case if thats it then we need to require the asset-admin via composer.
2. Do we have the flexibility to run it without, and I think we should not include the buttons if the asset admin is not there. 

I like the 2nd option.

**Comment by fonsekaean** [comment]
Also to add to that if we do the 2nd one then there is no point in displaying those buttons in the editor

**Comment by oilee80** [comment]
2nd option sounds good to me,
I've done a [cloudinary](https://github.com/MadeHQ/silverstripe-cloudinary) module but still need to integrate it with text editors

**Comment by fonsekaean** [comment]
Cool, I will take your MR and do some additional changes to support the 2nd option.

**Comment by fonsekaean** [comment]
Hello @oilee80 

Its taken a while to get back to you, I added a much workable solution on this MR https://github.com/SilverStripers/markdownfield/pull/22 and it work with both the cases where asset-admin is installed or not. 

Thanks for finding the issue 👍

**Pull request closed without merging**
